/* =========================================================================
 *  Mock Data — TVING Tech Meetup
 *  Schedule / Speakers 데이터는 이 파일 상단에 모아서 관리합니다.
 *  실제 운영 데이터로 교체할 때 이 배열만 수정하면 됩니다.
 * ========================================================================= */

const MEETUP_META = {
  edition: "Vol. 07",
  monthLabel: "May",
  dateText: "2026. 05. 26 (TUE) 14:00 – 18:30",
  venue: "티빙 사옥 1F 라운지 · 서울 마포구",
  capacity: "오프라인 120석 + 온라인 라이브",
  hostTeam: "Web Core Development",
  theme: "Streaming at Scale",
  themeKo: "스트리밍의 안쪽, 그 너머",
};

/* ---------- Schedule ---------- */
const SCHEDULE_DATA = [
  {
    time: "13:30",
    type: "register",
    title: "등록 및 네트워킹",
    desc: "사옥 1층 라운지에서 명찰을 받고 자유롭게 인사를 나눠요. 웰컴 키트와 커피가 준비돼 있습니다.",
    track: "ALL",
  },
  {
    time: "14:00",
    type: "opening",
    title: "Opening — 티빙이 만드는 K-콘텐츠 스트리밍의 오늘",
    speaker: "박지훈",
    role: "CTO, TVING",
    desc: "지난 1년간 가입자 1,000만을 돌파한 티빙의 기술 여정과, 다음 6개월의 방향을 짧게 공유합니다.",
    duration: "20m",
    track: "MAIN",
  },
  {
    time: "14:25",
    type: "session",
    title: "1,000만 동시 접속을 견디는 라이브 스트리밍 아키텍처",
    speaker: "정수민",
    role: "Live Platform Team",
    desc: "Prime Time에 몰리는 트래픽을 어떻게 받아내고, 어떻게 비용을 줄였는지 — 멀티 CDN, Edge 컴퓨팅, 적응형 비트레이트의 실전 튜닝 이야기.",
    duration: "30m",
    track: "INFRA",
    tags: ["Live", "CDN", "Edge"],
    keynote: true,
  },
  {
    time: "15:00",
    type: "session",
    title: "Next.js 15 App Router로 다시 짠 티빙 웹",
    speaker: "이가람",
    role: "Web Platform Team",
    desc: "Pages → App Router 마이그레이션 6개월. RSC가 실제로 가져다 준 것, 가져가지 못한 것, 그리고 우리가 새로 만든 캐시 전략.",
    duration: "30m",
    track: "WEB",
    tags: ["Next.js", "RSC", "Performance"],
  },
  {
    time: "15:35",
    type: "break",
    title: "Coffee Break",
    desc: "10분간 휴식. 라운지에 준비된 디저트와 함께 다음 세션을 기다려 주세요.",
    duration: "15m",
  },
  {
    time: "15:50",
    type: "session",
    title: "TVING 추천, LLM과 협업하는 법",
    speaker: "한도연",
    role: "ML Platform Team",
    desc: "프롬프트 기반 콘텐츠 추천 파이프라인을 프로덕션에 올리며 부딪힌 환각·지연·비용 문제와 우리가 고른 트레이드오프.",
    duration: "30m",
    track: "ML",
    tags: ["LLM", "Recommendation", "MLOps"],
  },
  {
    time: "16:25",
    type: "session",
    title: "디자인 시스템을 코드로 운영하기 — Refine의 1년",
    speaker: "오민채",
    role: "Design Engineering",
    desc: "사내 어드민 240개 화면을 단일 토큰 시스템으로 묶기까지. Figma–코드 양방향 동기화와 컴포넌트 거버넌스의 현실.",
    duration: "30m",
    track: "DESIGN",
    tags: ["DesignOps", "Tokens", "Figma"],
  },
  {
    time: "17:00",
    type: "session",
    title: "광고와 콘텐츠 사이 — 미드롤 삽입의 ML 파이프라인",
    speaker: "김서윤",
    role: "Ad Platform Team",
    desc: "한 편의 드라마를 끊지 않으면서도 광고 효율을 끌어올리는 자동 미드롤 포인트 탐지. 학습 데이터부터 A/B까지.",
    duration: "30m",
    track: "ADS",
    tags: ["Ads", "Video AI"],
  },
  {
    time: "17:35",
    type: "lightning",
    title: "Lightning Talks ⚡ — 4 × 5분",
    desc: "사내 엔지니어들이 5분 안에 풀어내는 짧고 진한 이야기. 주제는 당일 추첨!",
    duration: "25m",
    track: "ALL",
  },
  {
    time: "18:05",
    type: "closing",
    title: "Closing & Networking Party 🥂",
    desc: "맥주와 함께 자유롭게 이야기 나누는 시간. 발표자 전원이 라운지에 있습니다.",
    duration: "25m",
    track: "ALL",
  },
];

/* ---------- Speakers ---------- */
/*  사진은 picsum.photos seed 기반 placeholder. 실제 운영 시 교체.  */
const SPEAKER_DATA = [
  {
    id: "park-jihoon",
    name: "박지훈",
    nameEn: "Jihoon Park",
    team: "Office of CTO",
    role: "CTO",
    topic: "Opening Keynote",
    bio: "티빙의 기술 조직을 이끕니다. 이전에는 카카오, 라인에서 미디어 플랫폼을 만들었어요.",
    photo: (typeof window !== 'undefined' && window.__resources?.spk1) || "speakers/spk1.svg",
    accent: "from-rose-500/30 to-transparent",
  },
  {
    id: "jung-sumin",
    name: "정수민",
    nameEn: "Sumin Jung",
    team: "Live Platform",
    role: "Tech Lead",
    topic: "1,000만 동시 접속을 견디는 라이브 스트리밍 아키텍처",
    bio: "라이브 송출, CDN 라우팅, ABR을 만집니다. 야구 중계 시즌이 가장 바쁜 사람.",
    photo: (typeof window !== 'undefined' && window.__resources?.spk2) || "speakers/spk2.svg",
    accent: "from-red-500/30 to-transparent",
  },
  {
    id: "lee-garam",
    name: "이가람",
    nameEn: "Garam Lee",
    team: "Web Platform",
    role: "Senior Engineer",
    topic: "Next.js 15 App Router로 다시 짠 티빙 웹",
    bio: "tving.com 웹 전반과 디자인 시스템 연동을 담당합니다. RSC를 너무 좋아함.",
    photo: (typeof window !== 'undefined' && window.__resources?.spk3) || "speakers/spk3.svg",
    accent: "from-amber-500/30 to-transparent",
  },
  {
    id: "han-doyeon",
    name: "한도연",
    nameEn: "Doyeon Han",
    team: "ML Platform",
    role: "ML Engineer",
    topic: "TVING 추천, LLM과 협업하는 법",
    bio: "추천 모델과 프롬프트 파이프라인을 운영합니다. 가장 좋아하는 단어는 'eval'.",
    photo: (typeof window !== 'undefined' && window.__resources?.spk4) || "speakers/spk4.svg",
    accent: "from-violet-500/30 to-transparent",
  },
  {
    id: "oh-minchae",
    name: "오민채",
    nameEn: "Minchae Oh",
    team: "Design Engineering",
    role: "Design Engineer",
    topic: "디자인 시스템을 코드로 운영하기 — Refine의 1년",
    bio: "디자이너와 개발자 사이를 잇는 일을 합니다. Figma 플러그인 컬렉터.",
    photo: (typeof window !== 'undefined' && window.__resources?.spk5) || "speakers/spk5.svg",
    accent: "from-blue-500/30 to-transparent",
  },
  {
    id: "kim-seoyoon",
    name: "김서윤",
    nameEn: "Seoyoon Kim",
    team: "Ad Platform",
    role: "ML Engineer",
    topic: "광고와 콘텐츠 사이 — 미드롤 삽입의 ML 파이프라인",
    bio: "비디오 AI로 광고 삽입 지점을 찾는 시스템을 운영합니다. 영화 보면서 일하는 사람.",
    photo: (typeof window !== 'undefined' && window.__resources?.spk6) || "speakers/spk6.svg",
    accent: "from-emerald-500/30 to-transparent",
  },
];

/* expose to window (Babel scripts don't share scope) */
Object.assign(window, { MEETUP_META, SCHEDULE_DATA, SPEAKER_DATA });
